export const data = [
  [{
      id: 1,
      name: 'Звери - До скорой встречи',
      description: '«Зве́ри» — российская поп-рок-группа, созданная Романом Билыком в 2001 году. Лауреат премии MTV Россия и премии «Дебют». На премии Муз-ТВ группа побеждала в номинации «Лучшая рок-группа» 9 раз.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg/548px-Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg',
      audio: `https://ru-drivemusic.net/dl/4juevt4KhEFDqVQessBzAg/1596754740/download_music/2013/12/zveri-do-skorojj-vstrechi.mp3`,
      activeClass: '',
    },
    {
      id: 2,
      name: 'Смысловые галлюцинации - Вечно молодой',
      description: 'Советская и российская рок-группа из Екатеринбурга. Первоначально относилась к панк-рок-группам Свердловска, позднее стиль группы стал тяготеть к пост-панку и инди-року.',
      image: 'https://sefon.fm/img/artist_photos/smyslovye-gallyutsinatsii.jpg',
      audio: `https://ru-drivemusic.net/dl/mjYOkSfFv_NYjnbL3jrrOA/1596754782/download_music/2020/05/smyslovye-galljucinacii-vechno-molodojj.mp3`,
      activeClass: '',
    },
    {
      id: 3,
      name: 'Виктор Цой - Звезда по имени солнце',
      description: 'Советский рок-музыкант, автор песен и художник. Основатель и лидер рок-группы «Кино», в которой пел, играл на гитаре и являлся автором песен.',
      image: 'https://regnum.ru/uploads/pictures/news/2019/08/15/regnum_picture_1565864211125005_normal.jpg',
      audio: `https://ru-drivemusic.net/dl/H-t-qjvGp1aiYR76DISwpg/1596754806/download_music/2020/06/kino-zvezda-po-imeni-solnce.mp3`,
      activeClass: '',
    },
    {
      id: 4,
      name: 'Макс Корж - Разнесем',
      description: 'Белорусский певец и автор песен',
      image: 'https://www.verstov.info/uploads/posts/2016-11/1478167401_am9pqzdpcgc.jpg',
      audio: `https://ru-drivemusic.net/dl/7W4izIJCXE_OpTb6VV9rFg/1596754837/download_music/2020/01/maks-korzh-raznesem.mp3`,
      activeClass: '',
    },
    {
      id: 5,
      name: 'Чичерина Юлия - Жара',
      description: 'Российская рок-певица, музыкант, актриса, автор и исполнительница своих песен. Её творчество относится к волне российской музыкальной культуры «Уральский рок», наряду с группами «Сансара» и «Смысловые галлюцинации».',
      image: 'https://24smi.org/public/media/resize/800x-/2018/1/10/d25f4cbd4cc4d2bf70cf55fcdcc3171b.jpeg',
      audio: `https://ru-drivemusic.net/dl/tdrLdaShRhMBr2DflhTfyg/1596754859/download_music/2011/12/julija-chicherina-zhara.mp3`,
      activeClass: '',
    },
    {
      id: 6,
      name: 'Жуки - Батарейка',
      description: 'Советская и российская рок-группа, основанная в 1991 году. Основатель и руководитель группы — Валерий Жуков.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0_%D0%96%D1%83%D0%BA%D0%B8.jpg/548px-%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0_%D0%96%D1%83%D0%BA%D0%B8.jpg',
      audio: `https://ru-drivemusic.net/dl/anT0AelmN8aC72Cwnh6mgw/1596754878/download_music/2013/01/zhuki-batarejjka.mp3`,
      activeClass: '',
    },
  ],
  [{
      id: 1,
      name: "Miley Cyrus - See You Again",
      description: 'Aмериканская певица, автор песен и актриса.',
      image: 'https://www.alux.com/wp-content/uploads/2017/02/miley-cyrus-net-worth-300x300.jpg',
      audio: `https://ru-drivemusic.net/dl/i35lgaH6V4WAFtaFsPOn3Q/1596755236/download_music/2014/07/miley-cyrus-see-you-again.mp3`,
      activeClass: '',
    },
    {
      id: 2,
      name: 'Sia - Chandelier',
      description: 'Aвстралийская певица и автор песен в стиле эмоциональный джаз и поп, а также актриса.',
      image: 'https://www.notediscover.com/art/track/sia-never-give-up-77329.jpg',
      audio: `https://ru-drivemusic.net/dl/I1U-RueszUOM6mvXpwXH0w/1596755267/download_music/2014/03/sia-chandelier.mp3`,
      activeClass: '',
    },
    {
      id: 3,
      name: 'Adele - Skyfall',
      description: 'Британская певица, автор-исполнитель и поэт, лауреат 15 премий Грэмми.',
      image: 'https://lh3.googleusercontent.com/proxy/b-k_w-YqlnsKKYq27PSImI8eOsoewlF4sB7joMPPnWq1O1plQmdugfJfSiwCU-5olbtQuKtzKZprzS2T98ONCVYV8-OZA4OuHf2tICsHNFgo5Lo3XJniL6HEU9tfGxLB3g',
      audio: 'https://ru-drivemusic.net/dl/MSWoje0RyFXCNpKubPaHGA/1596755287/download_music/2012/10/adele-skyfall.mp3',
      activeClass: '',
    },
    {
      id: 4,
      name: 'Ed Sheeran - I See Fire',
      description: 'Британский поп-музыкант и актёр. Первый коммерческий успех пришёл к нему в июне 2011 года благодаря синглу «The A Team», занявшему третье место в британском чарте.',
      image: 'https://www.atlanticrecords.com/sites/g/files/g2000003466/f/201405/EdSheeran_ATLREC_ArtistCard300x300v3.jpg',
      audio: 'https://ru-drivemusic.net/dl/ib7euPuP4B7fGIZUrgy53Q/1596702284/download_music/2013/11/ed-sheeran-i-see-fire.mp3',
      activeClass: '',
    },
    {
      id: 5,
      name: 'Taylor Swift - Eyes Open',
      description: 'Американская кантри-поп-исполнительница, автор песен, музыкальный продюсер, режиссёр и актриса',
      image: 'https://dvd-fever.co.uk/dvd-fever/wp-content/uploads/2017/11/taylor-swift-reputation-300.jpg',
      audio: 'https://ru-drivemusic.net/dl/b15tgngWYfSqNcYw-jot6Q/1596702378/download_music/2012/03/taylor-swift-eyes-open.mp3',
      activeClass: '',
    },
    {
      id: 6,
      name: 'MIKA - Relax',
      description: 'Британский певец американo-ливанского происхождения.',
      image: 'https://note-store.ru/upload/resize_cache/iblock/902/325_380_2/MIKA.jpg',
      audio: 'https://ru-drivemusic.net/dl/oVBadFa5q0UB8rNFX3qkkg/1596702424/download_music/2013/12/mika-relax.mp3',
      activeClass: '',
    },
  ],
  [{
      id: 1,
      name: 'Miyagi - Моя банда',
      description: 'Российский хип-хоп-дуэт из города Владикавказ, Северная Осетия, образованный в 2015 году. Коллектив состоит из двух человек, известных под сценическими псевдонимами «Miyagi» — Азамат Кудзаев и «Andy Panda» — Сослан Бурнацев (Эндшпиль).',
      image: 'https://lh3.googleusercontent.com/proxy/sCumk7ietl-whbphtX34YCfmfahPA6dLT4YeYTOsMW29avDYndKP6CR8IRzbYSNEdfU44rlOE3dsa3GZYoTPHL97Ne4EjkKkIuFq9QkDf4CqwDLYMdGQ3YqRpF6b',
      audio: 'https://ru-drivemusic.net/dl/SzIBxI6i8E9JWnJicqHEpg/1596702476/download_music/2016/12/miyagi-jendshpil-feat.-mantana-moja-banda.mp3',
      activeClass: '',
    },
    {
      id: 2,
      name: 'Markul - B.I.D',
      description: 'Российский хип-хоп-исполнитель, певец, автор песен и член творческого объединения «Green Park Gang».',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Markul_%D0%BD%D0%B0_VK_Fest_5.jpg/548px-Markul_%D0%BD%D0%B0_VK_Fest_5.jpg',
      audio: 'https://ru-drivemusic.net/dl/fT93fqYhUbf2oznO6sW1LA/1596702524/download_music/2019/11/markul-b.i.d.mp3',
      activeClass: '',
    },
    {
      id: 3,
      name: 'Баста - Мама',
      description: 'Российский музыкант (исполнитель рэпа и других жанров, битмейкер, композитор), телерадиоведущий, актёр, сценарист, режиссёр и продюсер.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Basta_and_Guf_at_Green_Theatre_100721.jpg/500px-Basta_and_Guf_at_Green_Theatre_100721.jpg',
      audio: 'https://ru-drivemusic.net/dl/VSBZ0dXRmLax5lAkkCis3w/1596702608/download_music/2013/11/basta-mama.mp3',
      activeClass: '',
    },
    {
      id: 4,
      name: 'Каста - Радиосигналы',
      description: 'Pоссийская хип-хоп группа из Ростова-на-Дону, артисты лейбла Respect Production. В состав группы входят Влади, Шым, Хамиль, Змей.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/1_%D0%9A%D0%B0%D1%81%D1%82%D0%B0_photo_%40katya_mozina_001.jpg/548px-1_%D0%9A%D0%B0%D1%81%D1%82%D0%B0_photo_%40katya_mozina_001.jpg',
      audio: 'https://ru-drivemusic.net/dl/Z1DaJ6MefMjIxew5BX9GKw/1596756124/download_music/2014/03/kasta-radiosignaly.mp3',
      activeClass: '',
    },
    {
      id: 5,
      name: 'Мот feat. ВИА Гра - Кислород',
      description: 'Российский музыкант, рэпер.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/%D0%9C%D0%BE%D1%82_%D0%BD%D0%B0_Europa_Plus_TV._Hit_Non_Stop_%D0%B2_%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B5_2016.jpg/548px-%D0%9C%D0%BE%D1%82_%D0%BD%D0%B0_Europa_Plus_TV._Hit_Non_Stop_%D0%B2_%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B5_2016.jpg',
      audio: 'https://ru-drivemusic.net/dl/G6-3dBZEt00svfTIWHD52Q/1596756266/download_music/2014/11/mot-feat.-via-gra-kislorod.mp3',
      activeClass: '',
    },
    {
      id: 6,
      name: 'Макс Корж- Малиновый закат',
      description: 'Белорусский певец и автор песен',
      image: 'https://www.verstov.info/uploads/posts/2016-11/1478167401_am9pqzdpcgc.jpg',
      audio: 'https://ru-drivemusic.net/dl/gnB4VF8vCvzsbhWummjjnA/1596756324/download_music/2017/10/maks-korzh-malinovyjj-zakat.mp3',
      activeClass: '',
    },
  ],
  [{
      id: 1,
      name: 'Виктор Цой - Пачка сигарет',
      description: 'Советский рок-музыкант, автор песен и художник. Основатель и лидер рок-группы «Кино», в которой пел, играл на гитаре и являлся автором песен.',
      image: 'https://regnum.ru/uploads/pictures/news/2019/08/15/regnum_picture_1565864211125005_normal.jpg',
      audio: 'https://ru-drivemusic.net/dl/MelvGZlDO-eoW7qSFNYwHg/1596756923/download_music/2013/01/kino-pachka-sigaret.mp3',
      activeClass: '',
    },
    {
      id: 2,
      name: 'Звери - Все, Что Тебя Касается',
      description: '«Зве́ри» — российская поп-рок-группа, созданная Романом Билыком в 2001 году. Лауреат премии MTV Россия и премии «Дебют». На премии Муз-ТВ группа побеждала в номинации «Лучшая рок-группа» 9 раз.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg/548px-Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg',
      audio: 'https://ru-drivemusic.net/dl/yY3xl_qWkcUm5E-56Bp7yA/1596756972/download_music/2013/01/zveri-vse-chto-tebja-kasaetsja.mp3',
      activeClass: '',
    },
    {
      id: 3,
      name: 'Звери - Напитки покрепче',
      description: '«Зве́ри» — российская поп-рок-группа, созданная Романом Билыком в 2001 году. Лауреат премии MTV Россия и премии «Дебют». На премии Муз-ТВ группа побеждала в номинации «Лучшая рок-группа» 9 раз.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg/548px-Roman_Bilyk_in_Baku_%28Azerbaijan%29.jpg',
      audio: 'https://ru-drivemusic.net/dl/DOkTp7EVoacMFkDaOcUfwg/1596757063/download_music/2013/12/zveri-napitki-pokrepche.mp3',
      activeClass: '',
    },
    {
      id: 4,
      name: 'Би-2 - Лайки',
      description: 'Белорусско-российская рок-группа, образованная в 1988 году в Бобруйске.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/B2band_chartova_nazipov_2018.jpg/548px-B2band_chartova_nazipov_2018.jpg',
      audio: 'https://ru-drivemusic.net/dl/ymvbu4uF460Ztn3m0kPFtg/1596757187/download_music/2016/09/bi-2-lajjki.mp3',
      activeClass: '',
    },
    {
      id: 5,
      name: 'Альянс - На заре',
      description: 'Советская и российская рок-группа.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0_%C2%AB%D0%90%D0%BB%D1%8C%D1%8F%D0%BD%D1%81%C2%BB.jpg/548px-%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0_%C2%AB%D0%90%D0%BB%D1%8C%D1%8F%D0%BD%D1%81%C2%BB.jpg',
      audio: 'https://ru-drivemusic.net/dl/T7clfaesmP-1am2xIuzijQ/1596757217/download_music/2020/04/aljans-na-zare.mp3',
      activeClass: '',
    },
    {
      id: 6,
      name: 'Сплин - Орбит без сахара',
      description: 'Российская рок-группа из Санкт-Петербурга. Бессменный лидер — Александр Васильев. Датой рождения группы считается 27 мая 1994 года.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Splean-2010-07-30.jpg/500px-Splean-2010-07-30.jpg',
      audio: 'https://ru-drivemusic.net/dl/cI7YkLjgTOdtQND2x8Gg6Q/1596757258/download_music/2014/01/splin-orbit-bez-sakhara.mp3',
      activeClass: '',
    },
  ],
  [{
      id: 1,
      name: 'AWOLNATION - Sail',
      description: 'Американский коллектив, образованный в 2010 году Аароном Бруно. До AWOLNATION Бруно был участником Under the Influence of Giants, Hometown Hero и Insurgence.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AWOLNATION_in_performance_%28Los_Angeles%2C_2012%29.jpg/548px-AWOLNATION_in_performance_%28Los_Angeles%2C_2012%29.jpg',
      audio: 'https://ru-drivemusic.net/dl/yGhUQZU9X5kGr1hODYI_cw/1596757295/download_music/2014/07/awolnation-sail.mp3',
      activeClass: '',
    },
    {
      id: 2,
      name: 'Bloodhound Gang - The Bad Touch',
      description: 'Американская рок-группа из Филадельфии, начинавшая с хип-хопа под влиянием «Beastie Boys» и с ростом популярности начавшая использовать в музыке элементы фанка, рэпкор-метала и электроник-рока.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/The_Bloodhound_Gang.jpg/540px-The_Bloodhound_Gang.jpg',
      audio: 'https://ru-drivemusic.net/dl/3wZRwDoLULDGoU_eQn9ljg/1596757346/download_music/2014/02/bloodhound-gang-the-bad-touch.mp3',
      activeClass: '',
    },
    {
      id: 3,
      name: 'Evanescence - My Immortal',
      description: 'Американская рок-группа, основанная в 1995 году вокалисткой Эми Ли и гитаристом Беном Муди.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Evanescence_Members.jpg/470px-Evanescence_Members.jpg',
      audio: 'https://ru-drivemusic.net/dl/r8tI3MuEKzeJ56ZON7KzIg/1596757395/download_music/2014/07/evanescence-my-immortal.mp3',
      activeClass: '',
    },
    {
      id: 4,
      name: 'twenty one pilots - Stressed Out',
      description: 'Американский дуэт из Колумбуса, штат Огайо. Группа образовалась в 2009 году и на данный момент состоит из Тайлера Джозефа и Джоша Дана.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Twenty_One_Pilots%2C_Brixton_Academy%2C_London_%2824614299854%29_%28cropped%29.jpg/548px-Twenty_One_Pilots%2C_Brixton_Academy%2C_London_%2824614299854%29_%28cropped%29.jpg',
      audio: 'https://ru-drivemusic.net/dl/tFoZD7-VNBc0luQAuqxpxQ/1596757439/download_music/2015/05/twenty-one-pilots-stressed-out.mp3',
      activeClass: '',
    },
    {
      id: 5,
      name: 'The White Stripes - Seven Nation Army',
      description: 'американская рок-группа, образованная в 1997 году в Детройте, штат Мичиган. В состав The White Stripes с самого начала входили лишь два человека: Джек Уайт — гитарист, пианист и вокалист, и Мег Уайт — барабанщица-перкуссионистка, иногда исполняющая бэк-вокал.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Meg_%26_Jack%2C_The_White_Stripes.jpg/540px-Meg_%26_Jack%2C_The_White_Stripes.jpg',
      audio: 'https://ru-drivemusic.net/dl/F1WWHAqDAzgdayt3RxdaDg/1596757482/download_music/2018/03/the-white-stripes-seven-nation-army.mp3',
      activeClass: '',
    },
    {
      id: 6,
      name: 'Nirvana - About a Girl',
      description: 'Американская рок-группа, созданная вокалистом и гитаристом Куртом Кобейном и басистом Кристом Новоселичем в Абердине, штат Вашингтон, в 1987 году.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Nirvana_around_1992.jpg',
      audio: 'https://ru-drivemusic.net/dl/bV0FSx1Q-VINoQWvvMTCWQ/1596757549/download_music/2019/05/nirvana-about-a-girl.mp3',
      activeClass: '',
    },
  ],
  [{
      id: 1,
      name: 'Rihanna - Rihanna',
      description: 'Барбадосская певица, актриса, музыкальный продюсер, модный дизайнер и филантроп. В 16 лет переехала в США, чтобы начать карьеру певицы.',
      image: 'https://thecelebritystatuscom.files.wordpress.com/2017/01/rihanna-needed_me_remixes-web-2016-g3l_int-300x300.jpg?w=300',
      audio: 'https://ru-drivemusic.net/dl/3srIUqq1aSoFbHSWrqijLw/1596757977/download_music/2015/11/rihanna-rihanna-bitch-better-have-my-money.mp3',
      activeClass: '',
    },
    {
      id: 2,
      name: 'Lost Frequencies - Are You With Me',
      description: 'Бельгийский музыкальный продюсер и диджей.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/2016_Open_Beatz_-_Lost_Frequencies_-_by_2eight_-DSC_5232.jpg/548px-2016_Open_Beatz_-_Lost_Frequencies_-_by_2eight_-DSC_5232.jpg',
      audio: 'https://ru-drivemusic.net/dl/Sdwu-Ng4CO9hJLharyWN-Q/1596757613/download_music/2014/08/lost-frequencies-are-you-with-me-radio-edit.mp3',
      activeClass: '',
    },
    {
      id: 3,
      name: 'Saint Jhn - Roses (Latino Gang)',
      description: 'Американский рэпер, певец, композитор и музыкальный продюсер. Он выпустил свой первый студийный альбом, Collection One, в марте 2018 года.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/SAINt_JHN_.jpg/300px-SAINt_JHN_.jpg',
      audio: 'https://ru-drivemusic.net/dl/-0bywEZnUUSF6YHwztHDoQ/1596757696/download_music/2020/07/saint-jhn-feat.-j-balvin-roses-latino-gang-imanbek-remix.mp3',
      activeClass: '',
    },
    {
      id: 4,
      name: 'Era Istrefi - Bonbon',
      description: 'Косоварская певица и автор-исполнитель. Получила первую популярность среди албаноязычной аудитории в Европе после выпуска своего дебютного сингла «Mani për money» в 2013 году в возрасте 19 лет.',
      image: 'https://prostars.org/files/catalog/items/4/300x450/218/5d9eec0d318b6.png',
      audio: 'https://ru-drivemusic.net/dl/nuPIhSDqBV8e_ld0nsL8Xw/1596757736/download_music/2016/01/era-istrefi-bonbon.mp3',
      activeClass: '',
    },
    {
      id: 5,
      name: 'David Guetta feat. Sia - Titanium',
      description: 'Французский диджей и продюсер.',
      image: 'https://cdn0.likefm.ru/proxy/vardata/modules/musicdb/files/201410/40603f4bbd2af22f7a112d86e76efdaf.jpg?w=300&h=300&pos=center&t=1426067712',
      audio: 'https://ru-drivemusic.net/dl/eV_cXrO2YLrulgesZBil5Q/1596757815/download_music/2011/08/david-guetta-feat.-sia-titanium.mp3',
      activeClass: '',
    },
    {
      id: 6,
      name: 'Calvin Harris - Feel So Close',
      description: 'Шотландский автор-исполнитель, музыкальный продюсер и диджей.',
      image: 'https://cdn.shortpixel.ai/client/q_lqip,ret_wait/https://smotretklipy.ru/wp-content/uploads/2017/12/harris2-300x300.jpg',
      audio: 'https://ru-drivemusic.net/dl/2oU8aLDw_MKAZArAmWBNHg/1596757896/download_music/2011/07/calvin-harris-feel-so-close.mp3',
      activeClass: '',
    },
  ],
];